server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    username: ""
    password: ""
    url: "jdbc:h2:./taskManager"

  jpa:
    show-sql: true

logging:
  level:
    root: INFO
    web: DEBUG
