server:
  error:
    include-stacktrace: never

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    url: ${JDBC_DATABASE_URL}
#    username: ""
#    password: ""
#    url: "jdbc:h2:./taskManager"



  jpa:
    show-sql: false

logging:
  level:
    ROOT: INFO
