server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    username: "javaproject73"
    password: "javaproject73"
    url: "jdbc:postgresql://localhost:5411/javaproject73"

  jpa:
    show-sql: true

logging:
  level:
    root: INFO
    web: DEBUG
